library(viridis)
library(fields)
civ = cividis(256)
civ[1] = '#000000'
source('ContactsGen-v1.1.3.R')
farm = ContactsGen(rep(3,3), rep(10,9), example_rates, 1)
png('farm-heatmap.png', height = 1000, width = 1000)
image.plot(farm, col = civ, xaxt = 'n', yaxt = 'n', legend.lab = 'Relative Contact Rate', legend.cex = 4, legend.width = 3, axis.args = list(lwd.ticks = 0, at = c(0, max(farm)), labels = rep('',2)))
dev.off()
source('custom-contacts-gen-comparable.R')
png('facility-heatmap.png', height = 1000, width = 1000)
image.plot(shift_sum, col = civ, xaxt = 'n', yaxt = 'n', legend.lab = 'Relative Contact Rate', legend.cex = 4, legend.width = 3, axis.args = list(lwd.ticks = 0, at = c(0, max(shift_sum)), labels = rep('',2)))
dev.off()
